eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: hello-service
  zipkin:
    base-url: http://127.0.0.1:8082/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3386/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8080
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  logger:
    enabled: true