spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8080
          predicates:
          - Path=/service-a/**
          filters:
          - StripPrefix=1

server:
  port: 8888

