server:
  port: 8082
spring:
  application:
    name: service-logger
management:
   metrics:
     web:
       server:
       #避免访问zipkin页面报java.lang.IllegalArgumentException
         auto-time-requests: false