server:
  port: 8081

#开启熔断器
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-consumer
  sleuth:
    sampler:
       probability: 1.0 #2.0后percentage改为probability
  zipkin:
    base-url: http://127.0.0.1:8082/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3386/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
logging:
  pattern:
    console: "%date{HH:mm:ss.SSS} %-5level %-30.30logger{29} : %msg%n"
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  logger:
    enabled: true
